#project info
project:
  name: ivy-kiosk
  version: 1.0
  domain: http://localhost:8080

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kiosk
    username: root
    password: zofht11!!


  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
      ddl-auto: update # create, update, validate

logging:
  level:
    root: info
    com.ivy: debug
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    docExpansion: none
    tagsSorter: alpha
    operationsSorter: alpha
    path: /swagger-ui